###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: OMS UI Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build oms-ui
        run: |
          docker build . -t chidelmun/oms-ui:1.0.0
      - name: docker push
        run: |
          docker push chidelmun/oms-ui:1.0.0
